# Generated by Django 5.2.8 on 2026-04-22 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(help_text='Identifiant interne du cabinet (peut être imprimé sur le carnet).', max_length=32, unique=True)),
                ('notes_medicales', models.TextField(blank=True)),
                ('antecedents', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_page', models.PositiveIntegerField()),
                ('contenu', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['numero_page'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=16)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('symptomes', models.TextField(blank=True)),
                ('consultations_precedentes', models.TextField(blank=True)),
                ('statut_parcours', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('opere', 'Opéré'), ('termine', 'Terminé')], default='nouveau', max_length=16)),
                ('actif', models.BooleanField(default=True, help_text='Archivé = inactif.')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='dossiers/pieces_jointes/')),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
