# Generated by Django 5.2.8 on 2026-04-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avispatient',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecarnet',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='patients.dossierpatient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='infirmiere_referente',
            field=models.ForeignKey(blank=True, help_text='Infirmière référente (prise en charge / suivi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur associé (si le patient se connecte).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossierpatient',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dossier', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='avispatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='piecejointedossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='patients.dossierpatient'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecarnet',
            unique_together={('dossier', 'numero_page')},
        ),
    ]
