# Generated by Django 5.2.8 on 2026-04-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='infirmiere_referente',
            field=models.ForeignKey(blank=True, help_text='Infirmière référente (prise en charge / suivi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_suivis', to=settings.AUTH_USER_MODEL),
        ),
    ]
