# Generated by Django 5.2.8 on 2026-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_infirmiere_referente'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consultations_precedentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
