# Generated by Django 5.2.8 on 2026-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='derniere_consultation_date',
            field=models.DateField(blank=True, help_text='Date de la dernière consultation', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='derniere_consultation_details',
            field=models.TextField(blank=True, help_text='Détails de la dernière consultation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='derniere_consultation_lieu',
            field=models.CharField(blank=True, help_text='Lieu de la dernière consultation', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('inconnu', 'Inconnu')], default='inconnu', help_text='Groupe sanguin du patient', max_length=8),
        ),
    ]
