# Generated by Django 5.2.8 on 2026-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_derniere_consultation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='supprime_le',
            field=models.DateTimeField(blank=True, help_text='Date de mise à la corbeille (suppression douce).', null=True),
        ),
    ]
