# Generated by Django 5.2.8 on 2026-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_supprime_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo du patient (identification visuelle).', null=True, upload_to='patients/photos/'),
        ),
    ]
