# Generated by Django 5.2.8 on 2026-07-10 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='praticien_referent',
            field=models.ForeignKey(blank=True, help_text='Praticien référent (chirurgien-dentiste traitant).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_en_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
