# Generated by Django 5.2.8 on 2026-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='conseils',
            field=models.TextField(blank=True, help_text='Conseils donnés au patient (hygiène, alimentation, soins post-traitement...).'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='recommandations',
            field=models.TextField(blank=True, help_text='Recommandations complémentaires (suivi, examens, rendez-vous de contrôle...).'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='active', max_length=20),
        ),
    ]
