# Generated by Django 5.2.8 on 2026-04-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('rendez_vous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.dossierpatient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_praticien', to=settings.AUTH_USER_MODEL)),
                ('rendez_vous', models.OneToOneField(blank=True, help_text='Rendez-vous associé (si la consultation provient du planning).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='rendez_vous.rendezvous')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActeRealise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dent', models.CharField(blank=True, help_text='Optionnel: dent concernée (notation à préciser plus tard).', max_length=16)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='consultations.consultation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='consultations/photos/')),
                ('type_photo', models.CharField(choices=[('pre_op', 'Pré-opératoire'), ('post_op', 'Post-opératoire'), ('autre', 'Autre')], default='autre', max_length=16)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaDentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_dentaire', to='consultations.consultation')),
            ],
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date'], name='consultatio_date_0bc67a_idx'),
        ),
    ]
