# Generated by Django 5.2.8 on 2026-04-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.OneToOneField(blank=True, help_text='Rendez-vous associé (si la consultation provient du planning).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='rendez_vous.rendezvous'),
        ),
        migrations.AddField(
            model_name='acterealise',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='photoclinique',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='schemadentaire',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_dentaire', to='consultations.consultation'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['date'], name='consultatio_date_0bc67a_idx'),
        ),
    ]
