# Generated by Django 5.2.13 on 2026-07-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_appel_taux_absenteisme'),
        ('patients', '0005_patient_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviDouleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('intensite', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('localisation', models.CharField(blank=True, max_length=100)),
                ('type_douleur', models.CharField(choices=[('lancinante', 'Lancinante'), ('sourde', 'Sourde'), ('pulsatile', 'Pulsatile'), ('brulure', 'Brûlure'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('traitement_pris', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.RenameIndex(
            model_name='appel',
            new_name='consultatio_date_ap_199c10_idx',
            old_name='consultatio_date_ap_6a8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='appel',
            new_name='consultatio_patient_9ade78_idx',
            old_name='consultatio_patient_8c4e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='appel',
            new_name='consultatio_statut_1a9768_idx',
            old_name='consultatio_statut_2f91ac_idx',
        ),
        migrations.RenameIndex(
            model_name='tauxabsenteisme',
            new_name='consultatio_periode_04a2cc_idx',
            old_name='consultatio_periode_9d3e21_idx',
        ),
        migrations.RenameIndex(
            model_name='tauxabsenteisme',
            new_name='consultatio_type_pe_3a8e81_idx',
            old_name='consultatio_type_pe_4b7c82_idx',
        ),
        migrations.RenameIndex(
            model_name='tauxabsenteisme',
            new_name='consultatio_pratici_772f93_idx',
            old_name='consultatio_praticie_1a2f90_idx',
        ),
        migrations.AddField(
            model_name='suividouleur',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis_douleur', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='suividouleur',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_douleur', to='patients.patient'),
        ),
    ]
