# Generated by Django 5.2.8 on 2026-07-04 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('consultation', 'Consultation'), ('rendez_vous', 'Rendez-vous'), ('operation', 'Opération'), ('schema_dentaire', 'Schéma dentaire'), ('autre', 'Autre')], default='consultation', max_length=20)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID de la consultation/RDV source', null=True)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('contenu_ia_brut', models.TextField(blank=True, help_text='Texte IA original avant édition manuelle')),
                ('genere_par_ia', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes_rendus', to='patients.patient')),
                ('praticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_rediges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['patient', 'type_action'], name='comptes_ren_patient_86261d_idx')],
            },
        ),
    ]
