# Generated by Django 5.2.8 on 2026-04-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('confirme', 'Confirmé'), ('reporte', 'Reporté'), ('annule', 'Annulé'), ('absent', 'Absent'), ('effectue', 'Effectué')], default='programme', max_length=16)),
                ('motif_absence', models.CharField(blank=True, max_length=255)),
                ('raison_annulation', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_crees', to=settings.AUTH_USER_MODEL)),
                ('infirmiere', models.ForeignKey(blank=True, help_text='Infirmière associée (ex: préparation, suivi).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_infirmiere', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='patients.patient')),
                ('praticien', models.ForeignKey(blank=True, help_text='Chirurgien-dentiste (ou praticien) en charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_praticien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-debut'],
                'indexes': [models.Index(fields=['debut'], name='rendez_vous_debut_6900af_idx'), models.Index(fields=['statut'], name='rendez_vous_statut_fe48d4_idx')],
            },
        ),
    ]
