# Generated by Django 5.2.8 on 2026-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationinterne',
            name='niveau',
            field=models.CharField(choices=[('info', 'Info'), ('rappel', 'Rappel'), ('message', 'Message'), ('critique', 'Critique')], default='info', max_length=16),
        ),
    ]
