# Generated by Django 5.2.8 on 2026-06-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_notificationinterne_niveau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('date_heure', models.DateTimeField(help_text='Date et heure de la prochaine occurrence du rappel.')),
                ('recurrence', models.CharField(choices=[('aucune', 'Une seule fois'), ('quotidien', 'Tous les jours'), ('hebdomadaire', 'Toutes les semaines'), ('mensuel', 'Tous les mois')], default='aucune', max_length=16)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_heure'],
            },
        ),
    ]
