# Generated by Django 5.2.8 on 2026-06-19 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('type_analyse', models.CharField(choices=[('symptomes', 'Analyse symptômes'), ('traitement', 'Suggestion traitement'), ('interaction', 'Vérification interactions'), ('diagnostic', 'Aide diagnostic')], max_length=20)),
                ('donnees_entree', models.JSONField()),
                ('resultat', models.JSONField()),
                ('confiance', models.FloatField()),
                ('plateforme', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ConversationIA',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('plateforme', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('contexte', models.JSONField(default=dict)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_original', models.FileField(upload_to='ocr/original/')),
                ('fichier_traite', models.FileField(blank=True, null=True, upload_to='ocr/processed/')),
                ('texte_extrait', models.TextField()),
                ('metadonnees', models.JSONField(default=dict)),
                ('confiance', models.FloatField()),
                ('plateforme', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(choices=[('user', 'User'), ('ia', 'IA')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadonnees', models.JSONField(default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia_shared.conversationia')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RechercheIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('plateforme', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('resultat', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contexte', models.JSONField(default=dict)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=10)),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('voix_activee', models.BooleanField(default=False)),
                ('notifications_ia', models.BooleanField(default=True)),
                ('mode_expert', models.BooleanField(default=False)),
                ('sauvegarder_conversations', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'plateforme')},
            },
        ),
    ]
