# Generated by Django 5.2.8 on 2026-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, help_text='Dernière requête authentifiée (présence en ligne).', null=True),
        ),
    ]
