# Generated by Django 5.2.8 on 2026-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='langue_interface',
            field=models.CharField(default='fr', help_text="Langue préférée de l'interface (fr/en).", max_length=8),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mode_sombre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil utilisateur.', null=True, upload_to='profils/photos/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='preferences_notifications',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {'email': true, 'sms': false, 'push': true, 'rappels_auto': true}"),
        ),
    ]
