# Generated by Django 5.2.8 on 2026-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_utilisateur_derniere_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(blank=True, help_text="Date d'embauche (personnel uniquement).", null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.CharField(blank=True, help_text='Service de rattachement (personnel uniquement).', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='specialite',
            field=models.CharField(blank=True, help_text='Spécialité médicale (personnel uniquement).', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('suspendu', 'Suspendu')], default='actif', help_text='Statut RH (distinct de is_active, qui contrôle la connexion).', max_length=16),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('chirurgien_dentiste', 'Chirurgien-dentiste'), ('secretaire', 'Secrétaire'), ('infirmiere', 'Infirmière'), ('assistant', 'Assistant'), ('admin', 'Administrateur'), ('patient', 'Patient')], default='patient', help_text="Rôle fonctionnel pour les accès et l'expérience utilisateur.", max_length=32),
        ),
    ]
