# Generated by Django 5.2.8 on 2026-04-21 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_utilisateur_langue_interface_utilisateur_mode_sombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_valide_par_chirurgien',
            field=models.BooleanField(default=True, help_text='Pour le personnel créé par une secrétaire, validation du chirurgien requise.'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('utilise', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
