# Generated by Django 5.2.8 on 2026-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_utilisateur_date_embauche_utilisateur_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='theme_couleur',
            field=models.CharField(choices=[('bleu', 'Bleu'), ('vert', 'Vert'), ('rouge', 'Rouge'), ('rose', 'Rose'), ('jaune', 'Jaune')], default='bleu', help_text="Thème de couleur appliqué à l'interface.", max_length=16),
        ),
    ]
