# Generated by Django 5.2.8 on 2026-06-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_utilisateur_theme_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fcm_token',
            field=models.CharField(blank=True, help_text="Jeton Firebase Cloud Messaging de l'appareil mobile actif (notifications push).", max_length=255),
        ),
    ]
