# Generated by Django 5.2.13 on 2026-07-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_utilisateur_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('mot_de_passe_temporaire', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('note_traitement', models.TextField(blank=True)),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
