# Generated by Django 5.2.13 on 2026-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_add_demande_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Signature manuscrite numérisée du praticien (PNG transparent recommandé).', null=True, upload_to='signatures/'),
        ),
    ]
