# Generated by Django 5.2.8 on 2026-04-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Ex: user.created, patient.assigned_nurse', max_length=64)),
                ('objet_type', models.CharField(blank=True, help_text='Ex: Utilisateur, Patient', max_length=64)),
                ('objet_id', models.CharField(blank=True, help_text="Id de l'objet concerné (string).", max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['action'], name='journaux_lo_action_f43cd3_idx'), models.Index(fields=['cree_le'], name='journaux_lo_cree_le_4a4ebf_idx')],
            },
        ),
    ]
