# Generated by Django 5.2.8 on 2026-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaux', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logactivite',
            name='message',
        ),
        migrations.AddField(
            model_name='logactivite',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='details',
            field=models.TextField(blank=True, help_text="Description détaillée de l'action"),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='type_action',
            field=models.CharField(choices=[('patient', 'Patient'), ('consultation', 'Consultation'), ('rendez_vous', 'Rendez-vous'), ('personnel', 'Personnel'), ('systeme', 'Système'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('ordonnance', 'Ordonnance'), ('analyse', 'Analyse')], default='systeme', max_length=50),
        ),
        migrations.AddField(
            model_name='logactivite',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logactivite',
            name='action',
            field=models.CharField(help_text='Ex: création_patient, modification_consultation', max_length=100),
        ),
        migrations.AlterField(
            model_name='logactivite',
            name='objet_id',
            field=models.CharField(blank=True, help_text="ID de l'objet concerné", max_length=64),
        ),
        migrations.AlterField(
            model_name='logactivite',
            name='objet_type',
            field=models.CharField(blank=True, help_text="Type d'objet concerné", max_length=64),
        ),
    ]
