# Generated by Django 5.2.8 on 2026-04-27 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(help_text='Date de la période')),
                ('type_avis', models.CharField(choices=[('consultation', 'Consultation'), ('traitement', 'Traitement'), ('accueil', 'Accueil'), ('installations', 'Installations'), ('personnel', 'Personnel'), ('general', 'Général')], max_length=20)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('note_distribution', models.JSONField(default=dict, help_text='Distribution des notes {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-periode'],
                'unique_together': {('periode', 'type_avis')},
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avis', models.CharField(choices=[('consultation', 'Consultation'), ('traitement', 'Traitement'), ('accueil', 'Accueil'), ('installations', 'Installations'), ('personnel', 'Personnel'), ('general', 'Général')], default='general', max_length=20)),
                ('note', models.IntegerField(help_text='Note sur 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titre', models.CharField(help_text="Titre de l'avis", max_length=200)),
                ('commentaire', models.TextField(help_text='Commentaire détaillé')),
                ('points_positifs', models.JSONField(blank=True, default=list, help_text='Liste des points positifs')),
                ('points_negatifs', models.JSONField(blank=True, default=list, help_text='Liste des points négatifs')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text="Suggestions d'amélioration")),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('modere', 'Modéré'), ('masque', 'Masqué'), ('signale', 'Signalé')], default='publie', max_length=20)),
                ('date_moderation', models.DateTimeField(blank=True, help_text='Date de modération', null=True)),
                ('motif_moderation', models.TextField(blank=True, help_text='Motif de la modération')),
                ('nombre_signalements', models.IntegerField(default=0)),
                ('reponse_personnel', models.TextField(blank=True, help_text="Réponse du personnel à l'avis")),
                ('date_reponse', models.DateTimeField(blank=True, help_text='Date de la réponse', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_moderes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_donne', to=settings.AUTH_USER_MODEL)),
                ('reponse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_repondus', to=settings.AUTH_USER_MODEL)),
                ('signale_par', models.ManyToManyField(blank=True, related_name='avis_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['type_avis'], name='avis_avis_type_av_eb7588_idx'), models.Index(fields=['note'], name='avis_avis_note_b68d14_idx'), models.Index(fields=['statut'], name='avis_avis_statut_15db3a_idx'), models.Index(fields=['cree_le'], name='avis_avis_cree_le_9f70ba_idx')],
            },
        ),
    ]
